Add bigint
A-Dyu/first-term pull request #2
Opened 2020-06-25 21:51 UTC by A-Dyu

2020-06-26 16:10 UTC, kt-cpp requested changes
Код не смотрелся, работает на 1000мс дольше ограничения по времени

2020-06-29 20:24 UTC, kt-cpp requested changes

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.h
> +    std::vector<uint32_t> dig;
[minor] Буквы в именах переменных по талонам уже?) Почему не `digits`?

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.h
> +    explicit big_integer(std::string);
Не вижу причин принимать строку не по константной ссылке

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.h
> +    big_integer const operator--(int);
Что за дикий `const`, при возврате по ссылке?

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.h
> +    friend bool operator>=(big_integer const&, big_integer const&);
[note] Можно делать не через `friend` функцию, а через функции класса. А в в данных просто перевызвать их, они нужны лишь чтобы можно было сделать неявный каст левого аргумента до бигинта, а не только правого

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.h
> +    void dif(big_integer const&, size_t);
[minor] Может быть `diff``?

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +// Compare bigint with shifted suffix of other bigint
[minor] Больше комментариев и желательно отражающий суть)

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        auto res = static_cast<uint64_t>(x - y - c);
Вычитание происходит в `uint32_t`, а не так, как ты ожидаешь

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        c = (y + c > x);
`y + c` может переполниться в `uint32_t`

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        dig[start + i] = static_cast<uint32_t>(res & UINT32_MAX);
[minor] Вынеси данную операцию в отдельную функцию

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        x = (c << 32) | dig[dig.size() - 1 - i];
[note] `reverse_iterator`

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        dig[start + i] = static_cast<uint32_t>(res & UINT32_MAX);
Везде по коду

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (x) {
[minor] Пожалуйста используйте логические сравнения для интегральных типов по коду

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +void big_integer::append_substr(std::string const& s) {
Хочу `assert` на длину строки

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +std::string to_string(big_integer x) {
[minor] Нет смысла принимать по значению

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
[note] Можно ускорить используя `1'000'000'000` в качестве делителя

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
А так же использовать `mod_short` вместо просто `%`

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (unsigned int & d : res.dig) {
`uint32_t`

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
>  }
[note] Можно сделать функцию `.negate()`, которая будет менять in-place, а тут перевызвать. Аналогично с `operator ~`, и многими другими функциями (например сдвигами) тогда в каждой из них можно будет сделать минимум копирований

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return a + (-b);
[note] Можно делать меньше копий руками поинвертуруя `b`, но будет больше копипасты

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    // Get digit of bigint after using abs without creating new bigint
[note] Можно коммент получше написать

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +                             static_cast<uint64_t>(res.dig[i + j]) + static_cast<uint64_t>(c);
[note] Можно сократить количество кастов до 2

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        res.dig[i + b.dig.size()] += c;
Рассказать почему тут нет переполнения

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        qt = static_cast<uint32_t>(x / y);
[minor] Вынести это чудо в отдельную функцию

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer b = _b.abs();
[note] Имя `a_abs` и подобные несёт больше смысла

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t qt = 0;
[minor] Где нормализация?

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        qt = static_cast<uint32_t>(x / y);
Если результат деления больше `UNIT32_MAX` (максимальная _цифра_), то нужно возвращать `UNIT32_MAX`. У тебя же вернётся непонятно что

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return a - (a / b) * b;
[note] Можно сделать функцию, которая возвращает div и mod, а в операторах просто возвращать что-то одно. Так будет меньше операций в `%`

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +void big_integer::bit_op(big_integer b, const std::function<uint32_t(uint32_t, uint32_t)>& op) {
[note] Можно на лету получать _цифры_, тогда не придётся принимать по значению и возможно избежать лишних копирований

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer& big_integer::operator+=(big_integer b) {
Тут тоже можно не принимать по значению `b`

2020-06-29 20:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (int i = (int) a.dig.size() - 1; i >= 0; i--) {
Кастить в `int` плохо

2020-06-29 22:28 UTC, A-Dyu commented on bigint/big_integer.h
> +    std::vector<uint32_t> dig;
fixed

2020-06-29 22:29 UTC, A-Dyu commented on bigint/big_integer.h
> +    explicit big_integer(std::string);
fixed

2020-06-29 22:38 UTC, A-Dyu commented on bigint/big_integer.h
> +    big_integer const operator--(int);
fixed

2020-06-29 22:39 UTC, A-Dyu commented on bigint/big_integer.h
> +    friend bool operator>=(big_integer const&, big_integer const&);
Не понял(

2020-06-29 22:40 UTC, A-Dyu commented on bigint/big_integer.h
> +    void dif(big_integer const&, size_t);
fixed

2020-06-29 22:50 UTC, A-Dyu commented on bigint/big_integer.cpp
> +// Compare bigint with shifted suffix of other bigint
fixed (?)

2020-06-29 22:53 UTC, A-Dyu commented on bigint/big_integer.cpp
> +        auto res = static_cast<uint64_t>(x - y - c);
fixed

2020-06-29 22:53 UTC, A-Dyu commented on bigint/big_integer.cpp
> +        c = (y + c > x);
fixed

2020-06-29 22:56 UTC, A-Dyu commented on bigint/big_integer.cpp
> +        dig[start + i] = static_cast<uint32_t>(res & UINT32_MAX);
fixed

2020-06-29 22:58 UTC, A-Dyu commented on bigint/big_integer.cpp
> +        x = (c << 32) | dig[dig.size() - 1 - i];
ignored (потому что bigint_opt)

2020-06-29 22:58 UTC, A-Dyu commented on bigint/big_integer.cpp
> +void big_integer::append_substr(std::string const& s) {
fixed

2020-06-29 23:00 UTC, A-Dyu commented on bigint/big_integer.cpp
> +    if (x) {
fixed

2020-06-29 23:02 UTC, A-Dyu commented on bigint/big_integer.cpp
> +std::string to_string(big_integer x) {
fixed

2020-06-29 23:15 UTC, A-Dyu commented on bigint/big_integer.cpp
> +    }
ignored

2020-06-29 23:16 UTC, A-Dyu commented on bigint/big_integer.cpp
> +    for (unsigned int & d : res.dig) {
fixed

2020-06-29 23:33 UTC, A-Dyu commented on bigint/big_integer.cpp
>  }
fixed

2020-06-30 01:03 UTC, A-Dyu commented on bigint/big_integer.cpp
> +    return a + (-b);
fixed

2020-06-30 01:03 UTC, A-Dyu commented on bigint/big_integer.cpp
> +    // Get digit of bigint after using abs without creating new bigint
fixed (?)

2020-06-30 01:05 UTC, A-Dyu commented on bigint/big_integer.cpp
> +                             static_cast<uint64_t>(res.dig[i + j]) + static_cast<uint64_t>(c);
fixed

2020-06-30 01:08 UTC, A-Dyu commented on bigint/big_integer.cpp
> +    uint32_t qt = 0;
Не осиливаю статью, чтобы понять, что нужно исправить и почему( Разве то как я делаю плохо? Работает же

2020-06-30 01:10 UTC, A-Dyu commented on bigint/big_integer.cpp
> +        res.dig[i + b.dig.size()] += c;
Тут нет переполнения потому что на момент прибавления, этот разряд равен 0 (заменил на присвоение, чтобы было понятнее)

2020-06-30 01:15 UTC, A-Dyu commented on bigint/big_integer.cpp
> +        qt = static_cast<uint32_t>(x / y);
fixed

2020-06-30 01:18 UTC, A-Dyu commented on bigint/big_integer.cpp
> +    big_integer b = _b.abs();
fixed

2020-06-30 01:18 UTC, A-Dyu commented on bigint/big_integer.cpp
> +    return a - (a / b) * b;
ignored (не осиливаю)

2020-06-30 01:21 UTC, A-Dyu commented on bigint/big_integer.cpp
> +        qt = static_cast<uint32_t>(x / y);
fixed

2020-06-30 01:21 UTC, A-Dyu commented on bigint/big_integer.cpp
> +void big_integer::bit_op(big_integer b, const std::function<uint32_t(uint32_t, uint32_t)>& op) {
fixed

2020-06-30 01:22 UTC, A-Dyu commented on bigint/big_integer.cpp
> +big_integer& big_integer::operator+=(big_integer b) {
fixed

2020-06-30 01:25 UTC, A-Dyu commented on bigint/big_integer.cpp
> +    for (int i = (int) a.dig.size() - 1; i >= 0; i--) {
fixed

2020-06-30 13:02 UTC, kt-cpp commented on bigint/big_integer.h
> +    friend bool operator>=(big_integer const&, big_integer const&);
Понял, но забил

2020-06-30 13:08 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t qt = 0;
Без неё работает медленнее деление, ибо ты ошибаешься в прикидке ответа чаще

2020-06-30 13:09 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        qt = static_cast<uint32_t>(x / y);
Не вынес

2020-06-30 13:30 UTC, kt-cpp commented on bigint/big_integer.cpp
>              c = mul >> 32;
[minor] Сюда бы приведение 64 в 32..

2020-06-30 13:30 UTC, kt-cpp commented on bigint/big_integer.cpp
>  }
Не везде, где можно было сделал, но ок

2020-06-30 14:25 UTC, A-Dyu commented on bigint/big_integer.cpp
>              c = mul >> 32;
fixed

2020-06-30 14:32 UTC, A-Dyu commented on bigint/big_integer.cpp
> +        qt = static_cast<uint32_t>(x / y);
fixed (2)

2020-06-30 15:01 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        qt = static_cast<uint32_t>(x / y);
Не совсем то, что имелось в виду но тоже норм

2020-06-30 15:01 UTC, kt-cpp approved these changes

2020-06-30 15:01 UTC, merged